name: Failed Workflow
run-name: ${{ github.actor }} is running Failed Workflow
on: [push]
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - run: |
          expr 1 + 1 > output.log
      - name: Upload output file 
        uses: actions/upload-artifact@v4
        with:
          name: output-log-file
          path: output.log
  download:
    runs-on: ubuntu-latest
    needs: upload
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: output-log-file
      - run: |
          cat output.log
      - name: The job has failed
        if: failure()
        run: echo "The job has failed"
